### ISSUE TITLE
Non Categorical Meta Variables

### ISSUE THREAD

**Issue by pbelmann** [meringlab/FlashWeave.jl#12]
Is it possible to use FlashWeave also with non-categorical Meta variable like temperature?
If this is the case and I provide a column like the one below, the variable is one-hot encoded.

```
Meta_Temp
40.000
42.000
43.000
43.000
43.000
36.000
36.000
```

If I provide it without the decimal point, it is not one-hot encoded.

**Comment by jtackm** [comment]
Yes, continuous meta-variables are supported. The preprocessing routine got confused by the high number of duplicates in this particular case, hence the spurious encoding. This should now be fixed - assuming you are still on master, could you try ```]up FlashWeave``` and see if things work?
