### ISSUE TITLE
Can FlashWeave be used for ASV Tables

### ISSUE THREAD

**Issue by NoahCooke** [meringlab/FlashWeave.jl#14]
Hello,

I am looking to use FlashWeave on an ASV table, as made in Dada2: http://benjjneb.github.io/dada2/tutorial.html

Is this compatible with FlashWeave?

Many thanks,

Noah

**Comment by jtackm** [comment]
Hi Noah,

Yes, the type of ecological unit should not matter. I haven't yet used FlashWeave with ASVs myself, but here is one example I'm aware of: https://www.biorxiv.org/content/10.1101/2020.02.20.958975v1.full

Cheers,
Janko
