### ISSUE TITLE
ArgumentError: number of rows of each array must match (got (46, 47))

### ISSUE THREAD

**Issue by lixiaopi1985** [meringlab/FlashWeave.jl#17]
Hi,

Thank you for developing this tool.

I ran into this error during normalization steps:

┌ Warning: 1 factor variable with more than two categories were detected (cul_type), splitting it into separate dummy variables (One Hot)
└ @ FlashWeave C:\Users\Xiaoping\.julia\packages\FlashWeave\16aV0\src\preprocessing.jl:63
┌ Warning: adaptive pseudo-counts for 1 samples were lower than machine precision due to insufficient counts, removing them
└ @ FlashWeave C:\Users\Xiaoping\.julia\packages\FlashWeave\16aV0\src\preprocessing.jl:125

ArgumentError: number of rows of each array must match (got (46, 47)).

Just wondering if the program should have taken care of it internally?

my code for running: learn_network(otu, meta, sensitive=true, heterogeneous=false, normalize=true, alpha=0.05, FDR=true)

Thanks

**Comment by jtackm** [comment]
Thanks for the report and sorry for the delay, I've been on vacation. This looks like a bug, but I'm having trouble reproducing it without seeing the input data set. Would it be possible for you to share it in an obfuscated/reduced form that still reproduces the error?

**Comment by lixiaopi1985** [comment]
Thank you for getting back to me. I can't find the data anymore to reproduce the issue, I must have deleted it or over-written it. I'll just close this issue for now.

**Comment by jtackm** [comment]
Sorry to hear that, feel free to re-open if the issue should arise again.
