### ISSUE TITLE
graph() function does not open up

### ISSUE THREAD

**Issue by thisisdomi** [meringlab/FlashWeave.jl#19]
Hello,

I'm using FlashWeave with julia-1.5.0. When executing:

data_path = "/home/dmerges/davos_networks/HMP_SRA_gut_small.tsv"
netw_results = learn_network(data_path, sensitive=true, heterogeneous=false)
graph(netw_results)
All I get is: {50, 50} undirected simple Int64 graph with Float64 weights

The same for my own OTu table.

Any ideas are very welcome.

Many thanks and cheers,
Dominik

**Comment by jtackm** [comment]
Hi,

Yes, this is expected. The `graph` function provides access to the weighted graph object that FlashWeave uses internally to store interactions. This object plays well with the Julia Graph ecosystem (see https://github.com/JuliaGraphs for a collection of packages) and can be used to run a variety of algorithms for downstream analysis.

I assume you wanted to plot the network? FlashWeave does not visualise, you either want to export the network via `save_network` and load it with a dedicated graph plotting software (for instance Cytoscape, Gephi or one of several python and R packages) or try to use the [GraphPlot.jl](https://github.com/JuliaGraphs/GraphPlot.jl) package directly with the graph object (I haven't used that one in a while, though).

Cheers,
Janko

**Comment by thisisdomi** [comment]
Great, thanks for the fast response!

**Comment by jtackm** [comment]
In the meantime I fixed the README example, it should be more clear now
