### ISSUE TITLE
Interpreting track_rejections output

### ISSUE THREAD

**Issue by michmmcknight** [meringlab/FlashWeave.jl#35]
I am wanting to explore the discarded edges from my network to determine which ones are the result of environmental variables and included the generations of a track_rejections file when running flashweave (see head of file below). I've gathered that the Edge column indicates the ID of the two nodes connected by the rejected edge, but am looking for clarification on the values in the Rejecting_set column. Is it correct to assume the numbers there also representative of node IDs? Any clarifications appreciated!

Edge	Rejecting_set	Stat	P_value	Num_tests	Perc_tested	Df	SuffPower
4986 <-> 4657	1400,3067,1106	0.0	1.0	1	0.14286	0	true
4986 <-> 4805	1400,3067,1106	0.0	1.0	1	0.14286	0	true
4986 <-> 3626	1400,3067,1106	0.0	1.0	1	0.14286	0	true
4986 <-> 4636	1400,3067,1106	0.0	1.0	1	0.14286	0	true
4986 <-> 2802	1400,3067,1106	0.0	1.0	1	0.14286	0	true

**Comment by jtackm** [comment]
Yes, you are correct. Did you provide meaningful OTU headers in your data files or to the 'learn_network' function? If yes, and the track_rejections file still only shows numerical node IDs, that would be a bug to fix.
