### ISSUE TITLE
Fail to install FlashWeave

### ISSUE THREAD

**Issue by SilasK** [meringlab/FlashWeave.jl#5]
I know this is not a problem of Flash Weave but I cannot install it because of failing to install Arpack

https://github.com/JuliaLinearAlgebra/Arpack.jl/issues/5

**Comment by jtackm** [comment]
Thanks for letting me know. Yes, it seems until the latest Arpack.jl release with [#43](https://github.com/JuliaLinearAlgebra/Arpack.jl/pull/43)  is tagged it is best to go with the recommended way of using FlashWeave with the official julia binaries from https://julialang.org/downloads/.

**Comment by jtackm** [comment]
We can reopen this if the problem persists in the next version of Arpack.jl
